### ISSUE TITLE
what's the purpose of the updateOutportSubscription and receivePacket in runtime.coffee

### ISSUE THREAD

**Issue by ddnionio** [noflo/noflo-runtime-base#21]
Hi, I am reading the code and don't understand the purpose of updateOutportSubscription  and receivePacket  in the src/protocol/runtime.coffee

1, updateOutportSubscription
We attach the outports with a  new socket in order to listen the outport event and sendAll to the client.
But the network of noflow will emit the similar event and the protocal/network.coffee will listen them and sendAll (subscribeNetwork in network.coffee). So what's the difference between them?

2, receivePacket  
When the client send the packet to the runtime, it will call this function eventually. 
But it attach the port with a new socket, emit event in the new socket, then detach the socket. No one listen the event. I can't understand why it did this.
```coffeescript\
    socket = noflo.internalSocket.createSocket()
    port = component.inPorts[internal.port]
    port.attach socket
    switch payload.event
      when 'connect' then socket.connect()
      when 'disconnect' then socket.disconnect()
      when 'begingroup' then socket.beginGroup payload.payload
      when 'endgroup' then socket.endGroup payload.payload
      when 'data' then socket.send payload.payload
    port.detach socket
```

**Comment by jonnor** [comment]
1) This is for listening to data sent out by the whole runtime (exported outports of top-level graph). Where as subscribeNetwork is for looking at data *inside* the NoFlo network/graph, including any intermediate processing steps, for debugging. 

2) This is for sending data into the whole runtime (exported inports of top-level component/graph). It injects the input data into the network of the component (which is usually a subgraph). It then flows through the network, and then when network sends something out we trigger 1)
