### ISSUE TITLE
When component loading fails, does not send componentsready

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-runtime-base#61]
This means that if a _single_ component fails to load, then any FBP client which expects componentsready, like Flowhub or fbp-spec will fails to talk to the runtime.

Because there is no stack associated with the error (just message), and the message does not contain the name of the faulty component, it is essentially impossible to find the issue from the client-side.
Need to use a debugger on the remote end...

**Comment by bergie** [comment]
This is correct, you'll either get `component:error` or `component:componentsready`. fbp-client (and hence fbp-spec handles this correctly).
