### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by paulburlumi** [noflo/noflo-runtime-base#96]
Can you clarify the license for this repository by adding a LICENSE file?
https://help.github.com/articles/adding-a-license-to-a-repository/
Many Thanks!

**Comment by bergie** [comment]
should not be necessary given that we already have it in the package metadata: https://github.com/noflo/noflo-runtime-base/blob/303b1770d88181be7e2744771d6c2444655495db/package.json#L13
