### ISSUE TITLE
Error objects serialized as {}

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-runtime-base#98]
In `runtime:packet` payloads an Error object sent from NoFlo gets serialized as `{}`. This breaks checking error (type/messages) using fbp-spec.

This is possibly also the case for `network:packet`, not certain. Could also be the case for Flowtrace serialization.

**Comment by bergie** [comment]
JavaScript errors are not serializable, so we will need to somehow recognize errors and serialize manually.

**Comment by bergie** [comment]
Handled in noflo-runtime-postmessage: https://github.com/noflo/noflo-runtime-postmessage/blob/master/runtime/postmessage.js#L48
